# -*- coding: utf-8 -*-
"""Cargando Datos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LPMGBUSXY8CNymUD6KNsAFBnHpFmcW3j
"""

asdfasgasdg